// Long-form articles rendered below each game table. These exist for readers
// who want the "why" behind the trainer's grading — and they give every game
// URL substantial unique text content in the prerendered HTML.

function BlackjackArticle() {
  return (
    <article className="seo-copy game-article">
      <h2>How to play blackjack — the thirty-second version</h2>
      <p>
        You and the dealer each get two cards; yours are face up, the dealer shows one. Number cards count face
        value, picture cards count 10, and an ace counts 11 or 1 — whichever helps. Your goal is a total closer to
        21 than the dealer&#39;s without going over. You act first: <strong>hit</strong> to take another card,{' '}
        <strong>stand</strong> to stop, <strong>double down</strong> to double your bet for exactly one more card,
        or <strong>split</strong> a pair into two hands. Then the dealer plays by fixed rules — here, drawing until
        reaching 17 or better and standing on all 17s. Go over 21 and you lose immediately, even if the dealer
        later busts too. A two-card 21 (&quot;blackjack&quot;) pays 3:2.
      </p>
      <h2>What this trainer grades, exactly</h2>
      <p>
        Every time you act, the trainer computes the expected value of all of your legal options — hit, stand,
        double, split — using a full recursive expected-value engine for a 6-deck game where the dealer stands on
        soft 17 and doubling after splits is allowed. It doesn&#39;t compare you to a memorized chart; it solves
        your exact hand against the dealer&#39;s upcard. If you picked anything other than the highest-EV option,
        the feedback panel shows both plays and the difference in dollars at your bet size. Over a session, those
        differences accumulate into your <em>actual</em> house edge, shown next to the theoretical 0.6% that
        perfect play achieves under these rules.
      </p>
      <h2>Why basic strategy is worth learning</h2>
      <p>
        Blackjack played perfectly gives the house about half a percent — the cheapest widely available game in
        the casino. Blackjack played by intuition typically gives the house 2–4%. The gap is entirely made of a
        few dozen recurring situations most players get wrong: hitting 12 against a dealer 2, doubling soft hands
        against small upcards, splitting 8s against a 10, hitting soft 18 against a 9. None of these are judgment
        calls — each has a single mathematically correct answer that never changes. Drill here until the correct
        play is automatic, then take the <a href="/card">pocket strategy card</a> with you.
      </p>
      <h2>Common myths this trainer will cure you of</h2>
      <p>
        <strong>&quot;The third-baseman&#39;s bad play took the dealer&#39;s bust card.&quot;</strong> Other
        players&#39; decisions are exactly as likely to help you as hurt you; the math of your decision is
        unchanged. <strong>&quot;I always stand on 16 — anything can bust.&quot;</strong> Against a dealer 7
        through ace, hitting 16 loses less than standing, every time. Losing less is the whole game.{' '}
        <strong>&quot;Take even money on blackjack against an ace.&quot;</strong> Even money is just insurance in
        disguise, and insurance is a roughly 7%-house-edge side bet no basic-strategy player should touch.{' '}
        <strong>&quot;I&#39;m due after five losses.&quot;</strong> The shoe has no memory of your results —
        streaks change nothing about the next hand. Study the full lesson in the{' '}
        <a href="/learn/blackjack">Strategy School</a>, including the complete chart generated by this site&#39;s
        own engine.
      </p>
    </article>
  );
}

function VideoPokerArticle() {
  return (
    <article className="seo-copy game-article">
      <h2>How video poker works</h2>
      <p>
        Five cards are dealt from a genuine, fairly shuffled 52-card deck. You choose which cards to hold; the
        machine replaces the rest with a single draw from the same deck, and the pay table on the glass settles
        the result. That&#39;s the entire game — one decision per hand — but it&#39;s a real decision with 32
        possible ways to hold, and the difference between the best hold and a plausible-looking second choice is
        often several percent of your bet.
      </p>
      <h2>What this trainer grades, exactly</h2>
      <p>
        After every deal, the trainer exhaustively evaluates all 32 holds against every possible draw — for a
        three-card draw that&#39;s over sixteen thousand outcomes per hold — and computes each hold&#39;s exact
        expected return under the selected pay table. Your choice is compared to the best one, and mistakes are
        priced in dollars. Four pay tables are offered: <strong>Jacks or Better 9/6</strong> (99.54% return),{' '}
        <strong>Bonus Poker 8/5</strong> (99.17%), <strong>Double Double Bonus 9/6</strong> (98.98%) and full-pay{' '}
        <strong>Deuces Wild</strong> (100.76% — with perfect play the player has the edge). You can also play up
        to ten hands at once, the way multi-hand machines deal one starting hand and draw each hand from its own
        fresh deck.
      </p>
      <h2>Why the pay table matters more than luck</h2>
      <p>
        Casinos routinely place identical games with different pay tables side by side. &quot;9/6&quot; Jacks or
        Better pays 9× on a full house and 6× on a flush and returns 99.54% to a perfect player; the 8/5 version
        of the very same game returns 97.30%. Nothing about the play changes — the stingier glass simply keeps an
        extra 2% of every dollar. Learning to read a pay table before sitting down is the single highest-value
        habit in machine gambling, and the <a href="/learn/paytables">pay-table lesson</a> walks through it
        column by column.
      </p>
      <h2>The holds people get wrong most</h2>
      <p>
        A <strong>low pair beats two high cards</strong>: holding 6-6 returns more than holding K-Q from the same
        hand, even though the high cards feel more promising. <strong>Four to a flush beats a low pair</strong>,
        but a <strong>high pair beats both</strong>. Dealt a pat straight that&#39;s also four to a royal flush,
        the math says <strong>break the straight</strong> — the royal chase is worth more than the sure thing. And
        in Deuces Wild, almost everything you know inverts: two pair is worthless, lone high cards are worthless,
        and a single deuce outvalues nearly any four cards you could keep beside it. The{' '}
        <a href="/learn/videopoker">Strategy School lesson</a> has the complete hold-priority ladder for every
        pay table offered here.
      </p>
    </article>
  );
}

function UthArticle() {
  return (
    <article className="seo-copy game-article">
      <h2>How Ultimate Texas Hold&#39;em works</h2>
      <p>
        You place two equal bets to start — an <strong>ante</strong> and a <strong>blind</strong> — then you and
        the dealer each receive two hole cards, with five community cards to come. At three points you get one
        chance to make a <strong>play bet</strong>: before the flop for 4× your ante, after the flop for 2×, or
        after all five community cards for 1× — and if you never bet, you must fold and forfeit ante and blind.
        Best five-card poker hand wins. The dealer needs a pair to &quot;qualify&quot;; when the dealer
        doesn&#39;t qualify, the ante pushes back to you no matter what. The blind only pays extra on wins with a
        straight or better — on smaller wins it pushes — which is the house&#39;s built-in fee on the game.
      </p>
      <h2>What this trainer grades, exactly</h2>
      <p>
        Preflop decisions are graded against the published optimal 4× raising range. Flop and river decisions are
        graded by direct enumeration: on the river the trainer plays your hand against all 990 possible dealer
        hole-card combinations and computes the exact value of betting 1× versus folding; on the flop it
        enumerates dealer hands and runouts the same way. When you check a hand that should have bet 4×, the
        feedback shows precisely how much expected value that timidity cost — usually far more than players
        expect.
      </p>
      <h2>The one idea that defines the game</h2>
      <p>
        Because the bet you&#39;re allowed shrinks from 4× to 2× to 1× as information arrives,{' '}
        <strong>waiting for certainty is the expensive habit</strong>. Optimal play raises 4× preflop with about
        38% of starting hands — every ace, most kings, many queens — because a 4× bet made with even a modest
        edge earns more than a safe 1× bet made with a big one. Played this way the game costs about 2.2% of one
        ante per hand, roughly half a percent of total money wagered, which makes properly played UTH one of the
        better table games in the casino. Played passively, it&#39;s one of the worst. The full decision rules,
        including the river &quot;count the dealer&#39;s outs&quot; test, are in the{' '}
        <a href="/learn/uth">Strategy School lesson</a>.
      </p>
    </article>
  );
}

function ThreeCardArticle() {
  return (
    <article className="seo-copy game-article">
      <h2>How Three Card Poker works</h2>
      <p>
        Post an <strong>ante</strong>, receive three cards, and make the game&#39;s only decision: fold and give
        up the ante, or place a <strong>play bet</strong> equal to the ante and compare hands with the dealer.
        Three-card hand rankings differ from regular poker — a straight beats a flush, because straights are
        rarer with three cards. The dealer needs queen-high or better to qualify; if the dealer doesn&#39;t
        qualify, your ante is paid even money and your play bet is returned regardless of what you hold. Land a
        straight or better and the <strong>ante bonus</strong> pays automatically — even if the dealer beats you.
      </p>
      <h2>What this trainer grades, exactly</h2>
      <p>
        For every hand you&#39;re dealt, the trainer enumerates all 18,424 possible dealer hands from the
        remaining 49 cards and computes the exact expected value of playing versus folding. The optimal line this
        produces is the famous <strong>Q-6-4 rule</strong>: play any hand of queen-6-4 or better, fold anything
        worse. Playing correctly holds the house edge to about 3.4% of the ante; playing every hand pushes it
        near 7.7%, and folding too much is just as costly in the other direction.
      </p>
      <h2>Why such a weak hand plays</h2>
      <p>
        Q-6-4 loses to a qualified dealer far more often than it wins — the reason it still plays is the roughly
        30% of dealer hands that fail to qualify and pay your ante automatically. Those free wins are worth just
        enough to carry a marginal hand over the line. That&#39;s also why hands below queen-high are automatic
        folds no matter how coordinated they look: without at least a queen you can&#39;t even beat the
        qualifying threshold, so you&#39;re relying almost entirely on dealer no-shows. The{' '}
        <a href="/learn/threecard">Strategy School lesson</a> covers the comparison rule, the qualification math
        and the ante-bonus schedule in detail.
      </p>
    </article>
  );
}

const ARTICLES: Record<string, () => JSX.Element> = {
  blackjack: BlackjackArticle,
  videopoker: VideoPokerArticle,
  uth: UthArticle,
  threecard: ThreeCardArticle,
};

export function GameArticle({ game }: { game: string }) {
  const Body = ARTICLES[game];
  return Body ? <Body /> : null;
}
