import { Fragment, useEffect, useState } from 'react';
import { GLOSSARY, GlossaryEntry, T, TermSheet, TermSheetCtx } from '../content/glossary';
import { Legend, StratChart, useBlackjackCharts } from '../components/BlackjackCharts';
import { BlackjackPayoutFigure, PaytableBarsFigure, VarianceFigure } from '../components/LessonFigures';
import { SITE_NAME } from '../config';
import { Byline, formatDate } from '../components/Byline';
import { ARTICLES, Article } from '../content/articles';

/** first-published / last-substantive-edit dates per lesson (drive bylines and Article JSON-LD) */
export const LESSON_DATES: Record<string, { published: string; updated: string }> = {
  '': { published: '2026-07-05', updated: '2026-07-17' },
  blackjack: { published: '2026-07-05', updated: '2026-07-07' },
  videopoker: { published: '2026-07-05', updated: '2026-07-06' },
  uth: { published: '2026-07-05', updated: '2026-07-06' },
  threecard: { published: '2026-07-05', updated: '2026-07-06' },
  slots: { published: '2026-07-07', updated: '2026-07-07' },
  bankroll: { published: '2026-07-17', updated: '2026-09-28' },
  paytables: { published: '2026-07-17', updated: '2026-09-28' },
  myths: { published: '2026-07-17', updated: '2026-07-17' },
  glossary: { published: '2026-07-06', updated: '2026-07-07' },
};

function GlossaryLesson() {
  return (
    <>
      <h1>The Glossary</h1>
      <Byline {...LESSON_DATES.glossary} />
      <p className="lede">
        Casino language, translated. Anywhere you see a{' '}
        <span className="term" data-tip="Just like this — hover or tap dotted words anywhere in the Strategy School.">
          dotted word
        </span>{' '}
        in the Strategy School you can hover (or tap) for a quick definition, or come here for the full story.
      </p>
      <dl className="glossary-list">
        {GLOSSARY.map((g) => (
          <div key={g.key} id={g.key} className="glossary-entry">
            <dt>{g.term}</dt>
            <dd>{g.long}</dd>
          </div>
        ))}
      </dl>
    </>
  );
}

// ---------------------------------------------------------------- lessons

function BlackjackLesson() {
  const charts = useBlackjackCharts();
  return (
    <>
      <h1>Blackjack Basic Strategy</h1>
      <Byline {...LESSON_DATES.blackjack} />
      <p className="lede">
        The goal of blackjack is simple: get closer to 21 than the dealer without going over (
        <T k="bust">busting</T>). After the deal you choose to <T k="hit-stand">hit or stand</T>, and sometimes to{' '}
        <T k="double">double down</T> or <T k="split">split</T>. Here&#39;s the good news: blackjack is a solved
        game. For every hand you can hold and every dealer <T k="upcard">upcard</T>, one choice is mathematically
        best — the complete answer is called <T k="basic-strategy">basic strategy</T>, and it fits on a chart.
      </p>
      <p className="lede">
        The charts below are <strong>generated by this site&#39;s own math engine</strong> — the same one that
        grades you at the table (6 decks, dealer stands on all 17s, double after split allowed, no surrender) — so
        what you study here is exactly what the trainer expects.
      </p>
      <h2>How to read the charts</h2>
      <p>
        Find your hand on the left, the dealer&#39;s upcard along the top, and do what the letter says. One idea
        explains most of the chart: <strong>a dealer showing 2–6 busts often</strong> (they must keep taking cards
        until 17), so you play conservatively and let them destroy themselves; <strong>a dealer showing 7–A
        usually finishes strong</strong>, so you take more risks to catch up.
      </p>
      <Legend />
      <h3>Hard totals (no ace, or the ace forced to count as 1)</h3>
      <StratChart rows={charts.hard} caption="Hard 8 and below: always hit. Hard 18 and up: always stand." />
      <h3>Soft totals (an ace counting as 11)</h3>
      <p>
        A <T k="soft-hand">soft hand</T> can&#39;t bust by taking one card — the ace just switches from 11 to 1 —
        so these hands play far more aggressively than the same number without an ace.
      </p>
      <StratChart rows={charts.soft} caption="Soft 21 is just 21 — stand." />
      <h3>Pairs</h3>
      <StratChart rows={charts.pairs} caption="P = split. Where there's no P, play the hand as its total." />
      <h2>The five rules people break most</h2>
      <ol>
        <li><strong>Always split aces and eights.</strong> Even against a 10 or ace. 16 is the worst total in the game — splitting turns it into two fresh hands.</li>
        <li><strong>Never split tens or fives.</strong> 20 already wins most hands; a pair of fives is just a 10 that would rather <T k="double">double</T>.</li>
        <li><strong>Double 11 against everything</strong> (under these rules), and 10 against everything except a dealer 10 or ace.</li>
        <li><strong>Hit soft 18 against 9, 10 or ace.</strong> A-7 feels safe, but standing on it against big cards loses money long-term. Against 3–6, double it.</li>
        <li><strong>Hit 12 against a dealer 2 or 3.</strong> Only start standing on 12 when the dealer shows 4, 5 or 6.</li>
      </ol>
      <p>
        Why bother? Played perfectly, blackjack&#39;s <T k="house-edge">house edge</T> is about half a percent —
        the best deal in the casino. Played by feel, most people give the house 2% or more. Same table, same cards:
        the difference is entirely in the decisions.
      </p>
      <p>
        Headed to a real table? Bookmark the <a href="/card">quick-reference strategy card</a> — just the charts,
        sized for a phone screen.
      </p>
      <a className="practice-cta" href="/blackjack">Practice blackjack →</a>
    </>
  );
}

function VideoPokerLesson() {
  return (
    <>
      <h1>Video Poker Strategy</h1>
      <Byline {...LESSON_DATES.videopoker} />
      <p className="lede">
        Video poker deals you five cards. You choose which to keep, and the machine <T k="draw">draws</T>{' '}
        replacements for the rest — one decision per hand, then the <T k="paytable">pay table</T> settles up.
        Unlike slots, everything is knowable: the odds come from a real 52-card deck and the payouts are posted on
        the glass. That makes video poker one of the few casino games where studying actually changes your{' '}
        <T k="return">return</T>.
      </p>
      <p className="lede">
        Each list below is a ladder of priorities: <strong>start at the top and stop at the first line that
        matches your hand — hold those cards and draw the rest.</strong>
      </p>

      <h2>Jacks or Better (9/6) — 99.54% return</h2>
      <p>
        The granddaddy. You win with a pair of jacks or better. &quot;9/6&quot; describes the pay table: full house
        pays 9×, flush pays 6× — always check for those two numbers, because the same game with an 8/5 table keeps
        an extra 1.2% of your money.
      </p>
      <ol>
        <li><T k="royal-flush">Royal flush</T>, straight flush, four of a kind — keep the whole hand</li>
        <li>Four to a royal flush (yes — even if it means breaking up a <T k="pat-hand">made</T> flush or straight)</li>
        <li>Full house, flush, straight, three of a kind</li>
        <li>Four to a straight flush</li>
        <li>Two pair</li>
        <li>High pair (jacks, queens, kings or aces)</li>
        <li>Three to a royal flush</li>
        <li>Four to a flush</li>
        <li>Low pair (10s or worse)</li>
        <li>Four to an open-ended straight (like 6-7-8-9, which any 5 or 10 completes)</li>
        <li>Two <T k="suited">suited</T> high cards</li>
        <li>Three to a straight flush</li>
        <li>Two unsuited high cards (holding three or more? keep just the lowest two)</li>
        <li>Suited 10-J, 10-Q or 10-K</li>
        <li>One high card (J, Q, K or A)</li>
        <li>Nothing — throw all five away</li>
      </ol>
      <p>
        The two most-missed lines: <strong>a low pair beats one or two lone high cards</strong> (line 9 beats 11
        and 13), and <strong>four to a flush beats a low pair</strong> — but a high pair beats them both.
      </p>

      <h2>Bonus Poker (8/5) — 99.17% return</h2>
      <p>
        Same game, one twist: four of a kind pays bonuses by rank (four aces 80×, four 2s–4s 40×), paid for with a
        smaller full house and flush. <strong>Play the Jacks or Better list above</strong> — the right play only
        differs in rare corners, and the trainer will flag those when they come up.
      </p>

      <h2>Double Double Bonus (9/6) — 98.98% return</h2>
      <p>
        Here the quad-chasing gets serious: four aces with a 2, 3 or 4 as the fifth card (the{' '}
        <T k="kicker">kicker</T>) pays a monster 400×. That changes real decisions:
      </p>
      <ol>
        <li><strong>Dealt three aces plus a 2/3/4? Hold all four cards</strong> — that little kicker is worth real money</li>
        <li>Four 2s–4s with an A–4 kicker: keep everything; with any other fifth card, keep just the four of a kind and draw for a premium kicker</li>
        <li><strong>Two pair where one pair is aces: keep only the aces.</strong> In Jacks or Better you&#39;d keep both pairs — here two pair pays a measly 1×, so the shot at four aces wins</li>
        <li>Everything else: play the Jacks or Better list</li>
      </ol>
      <p>The trade-off: bigger jackpots, more dry spells. Expect wilder swings (<T k="variance">variance</T>) than Jacks or Better.</p>

      <h2>Deuces Wild (full pay) — 100.76% return</h2>
      <p>
        All four 2s are <T k="wild-card">wild</T> — a 2 becomes whatever card helps most. Winning starts at three
        of a kind, and with perfect play the full-pay version returns <em>more than 100%</em>: the player has the
        edge. Strategy is organized by how many deuces you&#39;re dealt — <strong>the deuces themselves are almost
        always the most valuable thing in your hand:</strong>
      </p>
      <h3>Dealt four deuces</h3>
      <ol><li>Hold all four (200×). The fifth card is irrelevant</li></ol>
      <h3>Three deuces</h3>
      <ol>
        <li>Keep a made wild royal flush or five of a kind</li>
        <li>Otherwise hold <strong>just the three deuces</strong> and draw two</li>
      </ol>
      <h3>Two deuces</h3>
      <ol>
        <li>Keep any made four of a kind or better</li>
        <li>Keep four to a royal flush</li>
        <li>Otherwise hold <strong>just the two deuces</strong> — never keep a pair with them</li>
      </ol>
      <h3>One deuce</h3>
      <ol>
        <li>Keep any made three of a kind or better (deuce + a pair <em>is</em> three of a kind)</li>
        <li>Four to a royal; four to a straight flush</li>
        <li>Three to a royal; three to a straight flush with both natural cards 6-7 or higher</li>
        <li>Otherwise hold <strong>the deuce alone</strong> and draw four</li>
      </ol>
      <h3>No deuces</h3>
      <ol>
        <li>Keep made hands of three of a kind or better</li>
        <li>Four to a royal or straight flush</li>
        <li>One pair — and <strong>if you have two pair, keep only one of them</strong> (two pair pays nothing here)</li>
        <li>Four to a flush or open-ended straight; three to a royal or straight flush</li>
        <li>Nothing — draw five. Lone high cards are worthless in this game: there&#39;s no jacks-or-better payout to chase</li>
      </ol>
      <a className="practice-cta" href="/videopoker">Practice video poker →</a>
    </>
  );
}

function UthLesson() {
  return (
    <>
      <h1>Ultimate Texas Hold&#39;em Strategy</h1>
      <Byline {...LESSON_DATES.uth} />
      <p className="lede">
        You and the dealer each get two private <T k="hole-cards">hole cards</T>, share five{' '}
        <T k="board">community cards</T>, and the best five-card hand wins. To start you place two equal bets: an{' '}
        <T k="ante">ante</T> and a <T k="blind-bet">blind</T>. Then, at three points in the hand, you get one
        chance to add a <T k="play-bet">play bet</T> — and here&#39;s the twist that defines the whole game:{' '}
        <strong>the earlier you commit, the more you&#39;re allowed to bet.</strong> Before the flop you may bet
        4× your ante; after the flop only 2×; at the end just 1× — or fold and forfeit everything.
      </p>
      <p className="lede">
        So optimal play is aggressive: betting big early with any real advantage is exactly what the math rewards.
        Checking a strong hand &quot;to see what happens&quot; is the single most expensive habit in this game.
      </p>
      <h2>Decision 1 — Preflop: bet 4× or check</h2>
      <p>Looking only at your two cards, bet the full 4× (never less) with:</p>
      <ol>
        <li><strong>Any pair of 3s or better</strong> (a pair of 2s just checks)</li>
        <li><strong>Any hand containing an ace</strong></li>
        <li><strong>King-anything <T k="suited">suited</T></strong>; king + 5 or better offsuit</li>
        <li><strong>Queen + 6 or better suited</strong>; queen + 8 or better offsuit</li>
        <li><strong>Jack + 8 or better suited</strong>; jack + 10 offsuit</li>
      </ol>
      <p>
        Everything else checks. You&#39;ll raise about 38% of hands — if that feels reckless, you&#39;re doing it
        right. An ace-anything really is a favorite over a random dealer hand.
      </p>
      <h2>Decision 2 — After the flop: bet 2× or check</h2>
      <p>Three community cards are up. If you checked before, bet 2× now with:</p>
      <ol>
        <li><strong>Two pair or better</strong></li>
        <li><strong>A hidden pair</strong> — one of <em>your</em> cards pairs the board, or you hold a pocket pair (except 2s). Hidden matters: if the pair sits entirely on the board, the dealer has it too</li>
        <li><strong>Four to a flush</strong> when one of your suited cards is a 10 or higher</li>
      </ol>
      <h2>Decision 3 — The river: bet 1× or fold</h2>
      <p>All five community cards are up. Now it&#39;s bet 1× or surrender your ante and blind:</p>
      <ol>
        <li><strong>Any hidden pair or better — bet.</strong></li>
        <li>
          With nothing, count <T k="outs">dealer outs</T>: unseen cards that would give the dealer a pair that
          beats you. Fewer than 21 (of 45 unseen) — bet; otherwise fold. Rule of thumb: if the board itself is
          decent and your high cards compete, a 1× bet often loses less than folding, because ties{' '}
          <T k="push">push</T> and the dealer frequently fails to <T k="qualify">qualify</T>
        </li>
      </ol>
      <p>
        Folding always costs exactly 2 antes. The trainer computes the exact value of both choices on every river
        (all 990 possible dealer hands), so drill until that boundary is instinct.
      </p>
      <h2>Why the blind bet exists</h2>
      <p>
        The <T k="blind-bet">blind</T> only pays extra when you win with a straight or better — on ordinary wins it
        just pushes. It&#39;s effectively the house&#39;s fee, and big early play bets are how you offset it.
        Played optimally, the game keeps about 2.2% of one ante per hand (about 0.5% of all money you put in play —
        one of the better bets in the casino).
      </p>
      <a className="practice-cta" href="/uth">Practice Ultimate Texas Hold&#39;em →</a>
    </>
  );
}

function ThreeCardLesson() {
  return (
    <>
      <h1>Three Card Poker Strategy</h1>
      <Byline {...LESSON_DATES.threecard} />
      <p className="lede">
        The simplest dealer-vs-player poker game: place an <T k="ante">ante</T>, get three cards, then make the
        game&#39;s only decision — fold (give up the ante) or place a <T k="play-bet">play bet</T> equal to your
        ante and show down against the dealer. The entire optimal strategy is one sentence:{' '}
        <strong>play with queen-6-4 or better, fold anything worse.</strong>
      </p>
      <h2>How to read &quot;Q-6-4&quot;</h2>
      <p>
        Compare your three cards to queen-6-4, highest card first. Any pair or better always plays. Q-7-2 plays
        (your second card, 7, beats the 6 before the third card even matters). Q-6-4 exactly plays. Q-6-3 folds.
        J-10-9 folds — any hand without at least a queen is an automatic fold, no matter how pretty it looks.
      </p>
      <h2>Why does such a weak hand play?</h2>
      <p>
        Because of the <T k="qualify">qualification</T> rule: the dealer needs queen-high or better to
        &quot;open&quot;. When the dealer fails to qualify, your ante gets paid <em>even if your hand is
        garbage</em>, and the play bet is returned. Roughly 30% of dealer hands don&#39;t qualify — those free wins
        make marginal hands like Q-6-4 profitable. Playing every hand hands the house about 7.7%; the Q-6-4 line
        holds it to 3.4% of the ante.
      </p>
      <h2>The ante bonus is free money</h2>
      <p>
        Land a straight or better and the ante pays a bonus (straight 1×, <T k="quads-trips">trips</T> 4×, straight
        flush 5×) <strong>even when the dealer beats you</strong>. No decision needed — it&#39;s automatic, and
        it&#39;s why the game plays friendlier than its <T k="house-edge">house edge</T> suggests when the cards
        run hot.
      </p>
      <a className="practice-cta" href="/threecard">Practice Three Card Poker →</a>
    </>
  );
}

function SlotsLesson() {
  return (
    <>
      <h1>Slot Machines, Demystified</h1>
      <Byline {...LESSON_DATES.slots} />
      <p className="lede">
        Slots are the one game in this school with no strategy chart — once you press spin there are no decisions
        left to make, so nothing here will help you "beat" a slot machine. Nobody can. What this lesson <em>can</em>{' '}
        do is explain how the machines actually work: the <T k="rng">RNG</T>, the different machine types, which
        on-screen "progress" is real and which is theater, and what <T k="volatility">volatility</T> means for your
        wallet. Armed with that, you can answer the two questions that matter: <strong>do I want to play slots at
        all, and if so, which machines fit my budget and taste?</strong>
      </p>

      <h2>How a slot really works</h2>
      <p>
        Behind every modern slot is a <T k="rng">random number generator</T> producing thousands of numbers a
        second, whether anyone is playing or not. The instant you press spin, the current number determines the
        result; the reels then spin purely for drama. Which results are possible, and how often, is fixed by the
        game&#39;s internal math sheet: the mix of symbols on each virtual reel married to the{' '}
        <T k="paytable">pay table</T>. Together they set the machine&#39;s <T k="return">return (RTP)</T> — the
        percentage of all money bet that it pays back over its lifetime.
      </p>
      <p>Three consequences worth internalizing, because casinos profit from people not knowing them:</p>
      <ol>
        <li><strong>Every spin is independent.</strong> No machine is ever hot, cold, or "due." A jackpot can hit twice in ten minutes or not for years — the RNG has no memory of either.</li>
        <li><strong>Nothing you do changes the odds.</strong> Time of day, spin timing, bet rhythm, whether you use a player&#39;s card, whether someone just won — none of it moves the math. Changing the RTP of a real machine requires regulator-supervised paperwork, not a switch in the back office.</li>
        <li><strong>Near misses are choreography.</strong> Two jackpot symbols and a third just off the payline feels agonizingly close. It isn&#39;t — the outcome was decided before the reels moved, and games are deliberately staged to show you almost-wins.</li>
      </ol>
      <p>
        The other thing to know: unlike video poker, where the pay table tells you the exact return,{' '}
        <strong>a slot&#39;s RTP is invisible in a live casino.</strong> Two identical-looking machines side by
        side can be set to different returns. Typical reality: penny video slots keep roughly 8–12% of every bet,
        higher-denomination machines usually (not always) keep less, and online slots — which commonly publish
        RTP in their help screens — mostly run 94–97%. Compare that to the half-percent edge of studied blackjack
        or video poker and you understand why slots fund the casino&#39;s chandeliers.
      </p>

      <h2>The types of machines</h2>
      <p>Walk any slot floor and nearly everything fits one of a few families:</p>
      <ol>
        <li>
          <strong>Classic reel slots.</strong> Three reels, one to a few paylines, a simple pay table you can read
          in ten seconds. Fixed top prize, generally steadier behavior. One trap: many older-style machines pay a
          disproportionate jackpot only at max coins — if you play one, the last coin is usually the best-value
          coin.
        </li>
        <li>
          <strong>Video slots with paylines.</strong> Five video reels, dozens of paylines, plus wilds, scatters,
          free-spin rounds and bonus games. Most "wins" are partial — 40¢ back on a $1.20 spin, with fanfare.
          Betting fewer lines rarely changes the return per dollar; it just slows the game down (not a bad thing).
        </li>
        <li>
          <strong>"Ways" and cascading games.</strong> Instead of fixed lines, matching symbols on adjacent reels
          pay in any position — often tens of thousands of ways, sometimes with a reshuffling reel layout every
          spin. Winning symbols may vanish and let new ones drop in for chain reactions, with multipliers that grow
          during free spins. Exciting, and usually on the high-volatility end.
        </li>
        <li>
          <strong>Hold-and-respin games.</strong> Land enough trigger symbols (coins, orbs, pearls) and they lock
          in place while the rest of the screen respins, trying to fill the grid for escalating prizes. This
          family dominates modern floors — and it&#39;s where most of the &quot;progression&quot; theater below
          lives.
        </li>
        <li>
          <strong><T k="progressive">Progressives</T>.</strong> Part of every bet feeds a growing jackpot.{' '}
          <em>Standalone</em> machines feed their own meter; <em>local</em> links pool one casino&#39;s machines;{' '}
          <em>wide-area</em> networks link whole states into eight-figure prizes. The funding comes out of the
          base game: the giant linked jackpots are generally the worst everyday return on the floor, because a
          slice of your bet is financing a prize you almost certainly won&#39;t win. Check the fine print, too —
          some progressives require a minimum or maximum bet to be eligible at all.
        </li>
      </ol>

      <h2>Real progression vs. fake progression</h2>
      <p>
        Modern slots are covered in meters: pots filling with coins, gems collecting in a vault, firecrackers
        climbing toward a bonus. The industry itself splits these into two categories — <em>actual persistence</em>{' '}
        and <em>perceived persistence</em> — and the difference is worth real money.
      </p>
      <p>
        <strong>Real progression (persistent state):</strong> the meter is part of the game&#39;s math and carries
        between spins — and, crucially, between players. Collect 100 coins and a bonus genuinely triggers;
        the count survives when a player walks away. <T k="must-hit-by">Must-hit-by progressives</T> are the
        purest form: a printed ceiling the jackpot cannot pass. Real progression means a machine&#39;s current
        state changes its value — which is why a small tribe of advantage players walks the floor hunting machines
        abandoned with nearly-full meters. If a meter is real and nearly full, the previous player paid for most
        of your bonus.
      </p>
      <p>
        <strong>Fake progression (perceived persistence):</strong> the pot glows, swells and rattles — and none of
        it changes your odds by one cent. It&#39;s animation layered over the same independent RNG, engineered to
        make you feel a payoff building and make leaving the machine feel like abandoning an investment. It is
        currently the dominant design on casino floors precisely because it creates that feeling for free.
      </p>
      <p>How to tell them apart before you care:</p>
      <ol>
        <li><strong>Does the state survive?</strong> Real meters show a specific persistent count ("87/100 coins") that&#39;s still there when nobody&#39;s playing. Vague glows, pulses and "energy" filling a pot are theater.</li>
        <li><strong>Is there a printed guarantee?</strong> "Must hit by $500" is enforceable math. "Jackpot feels close!" is marketing.</li>
        <li><strong>Read the help screens.</strong> Real mechanics are spelled out in the rules pages, because regulators require it. If the rules never mention the meter affecting anything, it doesn&#39;t.</li>
      </ol>
      <p>
        One warning cuts both ways: fake progression is specifically designed to trigger sunk-cost feelings —
        &quot;I can&#39;t leave now, it&#39;s about to pop.&quot; If you find yourself thinking that at a machine
        whose meter isn&#39;t provably real, that&#39;s the machine playing you.
      </p>

      <h2>Low volatility vs. high volatility</h2>
      <p>
        Two machines can have identical returns and feel like completely different games. <T k="volatility">
        Volatility</T> is how the payback is distributed; <T k="hit-frequency">hit frequency</T> is how often
        anything pays at all.
      </p>
      <ol>
        <li><strong>Low volatility:</strong> frequent small wins, few huge ones. Your money erodes slowly and predictably; sessions last longer; you will almost never win big. Best for modest bankrolls, long relaxed sessions, and anyone who hates dry spells.</li>
        <li><strong>High volatility:</strong> long losing stretches punctuated by rare hits worth hundreds or thousands of bets. The only way to a genuinely big win — and the fastest way to an empty wallet. A common rule of thumb: bring 200–300 bets of bankroll if you want to survive a high-volatility machine&#39;s droughts.</li>
      </ol>
      <p>Casinos rarely label volatility on the floor, but you can estimate it from the glass:</p>
      <ol>
        <li><strong>Look at the pay table&#39;s spread.</strong> Top prize thousands of times the smallest win → high volatility. A flat table where the best prizes are modest multiples → low.</li>
        <li><strong>Big progressive or massive advertised max win</strong> (5,000×–50,000× online) → the base game is starved to fund it: high volatility.</li>
        <li><strong>Feature-stacked games</strong> — retriggering free spins, growing multipliers, full-screen jackpots — concentrate payback into rare events: higher volatility. Simple games with small frequent bonuses run lower.</li>
        <li><strong>Online, just look:</strong> most published help screens state volatility and RTP outright.</li>
      </ol>

      <h2>So — should you play slots?</h2>
      <p>
        Do the honest math first. Slots are the most expensive game in the casino not just because the edge is
        high but because the game is fast: a comfortable pace is 400–600 spins an hour. At $1.20 a spin and 500
        spins an hour, you&#39;re putting $600/hour through a machine that keeps, say, 10% — an expected cost of{' '}
        <strong>about $60 an hour</strong>. The same hour at quarter video poker with the strategy from this site
        costs an expected $3 or so; studied blackjack similar. Variance means any single night can beat those
        numbers badly in either direction — but that&#39;s the price tag on the sticker.
      </p>
      <p>If the lights and the jackpot dream are worth it to you — that&#39;s a legitimate answer! — buy the experience intelligently:</p>
      <ol>
        <li><strong>Decide what the session may cost before you sit down</strong>, treat it as an entertainment purchase, and never chase what the machine "owes" you. It owes you nothing; every spin is spin one.</li>
        <li><strong>Match volatility to your goal.</strong> Want two hours of fun on $50? Low volatility, small bets. Willing to lose your whole budget fast for a real shot at a big hit? High volatility — and expect the fast loss.</li>
        <li><strong>Skip the wide-area monsters</strong> unless the lottery-ticket dream is the whole point — you pay for that jackpot on every spin.</li>
        <li><strong>Check bet requirements.</strong> If a machine only awards its jackpot or bonus at max bet, either bet max on a lower denomination or pick a different machine.</li>
        <li><strong>Prefer machines that publish their numbers.</strong> Online slots disclose RTP and volatility; on a live floor, favoring simpler games and reading help screens is the closest you get.</li>
        <li><strong>Slow down.</strong> The house edge is charged per spin. Half the spins per hour is literally half the expected cost — the cheapest upgrade in the casino.</li>
      </ol>
      <p>
        And if what you actually enjoy is the machine format — sitting alone, pressing buttons, jackpot potential —
        consider <a href="/learn/videopoker">video poker</a>: the same cabinet experience with posted math, real
        decisions, and a house edge you can shrink to a twentieth of a slot&#39;s.
      </p>
      <a className="practice-cta" href="/videopoker">Try video poker — the slot that lets you fight back →</a>
    </>
  );
}

function BankrollLesson() {
  return (
    <>
      <h1>Bankroll &amp; Variance: The Math of Not Going Broke</h1>
      <Byline {...LESSON_DATES.bankroll} />
      <p className="lede">
        Strategy tells you the right play; bankroll math tells you what a session will actually feel like — and
        cost. This lesson puts numbers on the two forces at work every time you sit down: the{' '}
        <T k="house-edge">house edge</T>, which grinds slowly and predictably, and <T k="variance">variance</T>,
        which swings wildly and drowns the edge out in the short run. Understanding both is the difference between
        a planned evening and an ugly surprise.
      </p>

      <h2>Expected cost: the honest price tag</h2>
      <p>
        The long-run cost of any gambling session is simple multiplication:{' '}
        <strong>total money wagered × house edge</strong>. Not your buy-in — your total action. Bet $10 a hand at
        70 blackjack hands an hour and you&#39;re wagering $700/hour; at a 0.6% edge that costs about $4.20 an
        hour played perfectly. The same $10 on a slot at 500 spins an hour is $5,000/hour of action; at a 10%
        hold that&#39;s $500 an hour. Same bet size, hundred-times different price — because edge <em>and</em>{' '}
        speed both multiply. Slowing down is mathematically identical to finding a better game.
      </p>

      <h2>Variance: why one night proves nothing</h2>
      <p>
        Blackjack&#39;s standard deviation is about 1.15 bets per hand. Over 70 hands at $10, one standard
        deviation is roughly ±$95 — against an expected loss of about $4. The swing is twenty times the grind.
        That ratio is why people believe in hot tables and lucky rituals: in any single session, luck outweighs
        skill enormously, and a terrible player can crush a perfect one all night. But variance grows with the{' '}
        <em>square root</em> of hands played while expected loss grows linearly — over ten thousand hands the
        grind catches the swing, and after a hundred thousand the math is basically destiny. The casino plays the
        long game; a training site&#39;s job is to make sure your side of it is as cheap as possible.
      </p>
      <VarianceFigure />

      <h2>Sizing a session bankroll</h2>
      <p>
        A practical rule of thumb for surviving normal swings without sweating: bring roughly{' '}
        <strong>40–50 bets for blackjack or the poker-pit games</strong> (where each round risks a few bets at
        once), and <strong>200–300 bets for anything high-volatility</strong> like Double Double Bonus or slots.
        With $200 at a $10 blackjack table you have a real chance of a losing streak felling you before the
        evening is done; the fix is not courage, it&#39;s a $5 table. Three rules turn this into a system:
        decide the number before you play, never top up past it, and treat whatever is gone at the end as the
        purchase price of the entertainment — because mathematically, that&#39;s exactly what it was.
      </p>

      <h2>Betting systems don&#39;t work — here&#39;s the actual math</h2>
      <p>
        Every betting progression — Martingale (double after losses), and all their cousins —
        rearranges <em>when</em> you win and lose without changing the <T k="expected-value">expected value</T> of
        a single bet, which stays negative. The Martingale turns many small wins plus rare catastrophic losses
        into the same long-run cost: doubling $10 through a seven-loss streak has you betting $1,280 to win the
        original $10, and seven-loss streaks arrive far more often than intuition says — about once every 90
        sequences in an even-money game. No sequencing of negative-EV bets sums to a positive. The only levers
        that actually move your cost are the ones this site trains: game selection, rule selection, and playing
        each hand correctly.
      </p>
      <p>
        Watch it happen live: the trainer&#39;s stats panel tracks your total wagered, expected cost and actual
        result separately — a few hundred hands of watching those numbers diverge and reconverge teaches variance
        better than any formula.
      </p>
      <a className="practice-cta" href="/blackjack">Put it into practice →</a>
    </>
  );
}

function PaytablesLesson() {
  return (
    <>
      <h1>Reading Pay Tables: The Easiest Money in the Casino</h1>
      <Byline {...LESSON_DATES.paytables} />
      <p className="lede">
        Two identical-looking machines, side by side, same game, same bets — one quietly keeps two or three times
        as much of your money. The only difference is the <T k="paytable">pay table</T> posted on the glass, and
        casinos count on almost nobody reading it. Five minutes of learning what the numbers mean is worth more
        per hour than memorizing any strategy chart on this site.
      </p>

      <h2>Video poker: the two numbers that matter</h2>
      <p>
        Video poker pay tables are named by the full house and flush payouts, the two lines casinos shave first.
        For Jacks or Better, per coin: <strong>9/6 returns 99.54%</strong> with perfect play,{' '}
        <strong>8/6 returns 98.39%</strong>, <strong>8/5 returns 97.30%</strong>, and the sadly common{' '}
        <strong>7/5 returns 96.15%</strong>. Read that as an hourly price: at $1.25 a hand and 600 hands an hour,
        the 9/6 machine costs about $3.50/hour and the 7/5 machine about $29/hour — for exactly the same game
        played exactly the same way. Bonus-style games advertise bigger four-of-a-kind payouts, but the funding
        always comes from somewhere: Double Double Bonus pays two pair 1× instead of 2×, and that single line is
        most of why its <T k="return">return</T> is a point lower than it looks.
      </p>
      <PaytableBarsFigure />

      <h2>Max coins and the royal flush</h2>
      <p>
        One machine quirk matters enough to state as a rule: the <T k="royal-flush">royal flush</T> typically
        pays 250-per-coin at one to four coins but <strong>800-per-coin at five</strong>. Playing four coins
        forfeits about half a percent of return. Either play max coins on a denomination you can afford — five
        quarters beats one dollar-and-a-quarter on a dollar machine — or accept that you&#39;re paying extra for
        smaller swings.
      </p>

      <h2>Blackjack: the sign is a pay table too</h2>
      <p>
        The felt and the placard are blackjack&#39;s pay table, and one line towers over the rest:{' '}
        <strong>blackjack pays 3:2</strong> is a normal game, while <strong>6:5 adds about 1.4%</strong> to the
        house edge — more than tripling the cost of a well-played 6-deck game. No strategy adjustment can buy
        that back; the only correct response to a 6:5 table is to keep walking. The smaller print matters too:
        dealer hitting soft 17 costs about 0.2%, no double after split about 0.1%, and each rule is posted right
        there for anyone who looks. Two tables in the same pit routinely differ by half a percent — a 5x difference in the cost of your evening.
      </p>
      <BlackjackPayoutFigure />

      <h2>Side bets: where the edge hides</h2>
      <p>
        Almost every table game now sells side bets — Pair Plus, 21+3, Perfect Pairs, Trips — and they follow one
        iron rule: <strong>the flashier the payout column, the bigger the house edge</strong>. Typical side bets
        keep 2–8% (some far more), against 0.5% for the main game played well. They exist precisely because the
        main games have become such thin margins for the house. Budget them as entertainment if you enjoy them —
        but know that the casino considers them the profitable part of your visit.
      </p>

      <h2>The habit</h2>
      <p>
        Before money goes in anything: find the full house and flush numbers (or the blackjack payout line), and
        walk one machine further if they&#39;re short. Nothing else in gambling pays this well per second of
        effort. Then make sure your play is worthy of the good table you found — the{' '}
        <a href="/learn/videopoker">video poker</a> and <a href="/learn/blackjack">blackjack</a> lessons take it
        from here.
      </p>
      <a className="practice-cta" href="/videopoker">Practice on a full-pay machine →</a>
    </>
  );
}

function MythsLesson() {
  return (
    <>
      <h1>Casino Myths vs. the Math</h1>
      <Byline {...LESSON_DATES.myths} />
      <p className="lede">
        Every myth below survives because it <em>feels</em> true at a table, and because on any given night it can
        look true. The math says otherwise — checkably, in every case. This is the Strategy School&#39;s
        mythbusting reference: the beliefs that cost players the most, and exactly why each one is wrong.
      </p>

      <h2>&quot;The table/machine is due&quot;</h2>
      <p>
        The gambler&#39;s fallacy, and the most expensive sentence in gambling. Cards, dice and{' '}
        <T k="rng">RNGs</T> have no memory: after five losses, the sixth bet has exactly the odds it always had.
        Nothing is ever &quot;due,&quot; &quot;hot,&quot; or &quot;cold&quot; — streaks are what randomness looks
        like, not a signal inside it. The casino version of this myth runs both directions, and both are wrong
        for the same reason: independence.
      </p>

      <h2>&quot;Other players&#39; mistakes hurt me&quot;</h2>
      <p>
        The third-baseman who hits 16 against a 6 and &quot;takes the dealer&#39;s bust card&quot; is blackjack&#39;s
        favorite villain — and mathematically a ghost. An unknown card leaving the shoe is exactly as likely to
        help you as hurt you; over time, other players&#39; decisions have precisely zero effect on your{' '}
        <T k="expected-value">expected value</T>. The memorable nights when a bad play cost you a hand are real;
        the equally frequent nights it saved you just don&#39;t get remembered.
      </p>

      <h2>&quot;Insurance protects your good hands&quot;</h2>
      <p>
        Blackjack insurance is a separate side bet that the dealer&#39;s hole card is a ten — it pays 2:1 on a bet
        that wins less than one time in three, for a house edge around 7%. It doesn&#39;t &quot;protect&quot;
        anything; it&#39;s an unrelated bad bet stapled onto your good hand. &quot;Even money&quot; on your own
        blackjack is the same bet wearing a suit. Basic strategy&#39;s answer is one word: never.
      </p>

      <h2>&quot;Betting systems beat the house&quot;</h2>
      <p>
        No arrangement of negative-EV bets adds up to a positive — a progression can only reshape <em>when</em>{' '}
        the money moves, not <em>which way</em> it flows on average. The Martingale&#39;s occasional
        table-limit catastrophe pays for all its little wins, to the decimal. The full arithmetic is in the{' '}
        <a href="/learn/bankroll">bankroll lesson</a>. If a system truly worked, the casino wouldn&#39;t ban it —
        it would be the one dealing it.
      </p>

      <h2>&quot;Slots pay more at night / with a player&#39;s card out / after a jackpot&quot;</h2>
      <p>
        A slot&#39;s return is fixed in its math sheet and can&#39;t legally change spin to spin, card in or card
        out, midnight or noon. Changing a machine&#39;s programmed return involves regulator paperwork, not a
        switch in the back office. And a jackpot that just hit leaves the next spin&#39;s odds exactly where they
        were — <T k="progressive">progressive</T> meters aside, a machine that just paid is neither safer nor
        &quot;spent.&quot; The one honest exception is a <T k="must-hit-by">must-hit-by</T> progressive near its
        ceiling — covered in the <a href="/learn/slots">slots lesson</a>.
      </p>

      <h2>&quot;Card counting is illegal / counting is for geniuses / counting works online&quot;</h2>
      <p>
        Three myths in one. Counting cards with your own brain is legal everywhere in the US (casinos may still
        ask you to leave — private property). It isn&#39;t genius work either: keeping a running plus-minus count
        is a skill an attentive person can learn in a weekend, though disguising it well enough to survive is the
        hard part. And it cannot work online or on any continuously-shuffled game: counting exploits a shoe that
        deals deep without reshuffling, and a shuffle after every hand — physical or virtual — resets the count
        to zero permanently.
      </p>

      <h2>&quot;I have a feeling about this one&quot;</h2>
      <p>
        Every myth above is the same belief in different clothes: that attention, timing, or ritual can move
        odds that are fixed by arithmetic. The liberating flip side is that the arithmetic <em>is</em> movable —
        by game selection, by <a href="/learn/paytables">pay-table reading</a>, and by playing each hand
        correctly. Those are the only levers that exist. The good news: they&#39;re entirely learnable, and
        they&#39;re what the rest of this site is for.
      </p>
      <a className="practice-cta" href="/learn">Back to the Strategy School →</a>
    </>
  );
}

function LearnIndex() {
  return (
    <>
      <h1>The Strategy School</h1>
      <p className="lede">
        Never set foot in a casino? Start here. Every game on this site has a mathematically correct way to play
        it — worked out decades ago, checkable to the decimal. Study the lesson, then take it to the table: the
        trainer grades every decision against the same math and shows what each mistake costs. Dotted words like{' '}
        <T k="house-edge">house edge</T> have hover definitions, and the full <a href="/learn/glossary">glossary</a>{' '}
        translates all the casino jargon.
      </p>

      <h2>Casino 101: the house always wins — slowly</h2>
      <p>
        Every casino game pays winners slightly less than the true <T k="odds">odds</T> would suggest. That gap is
        the <T k="house-edge">house edge</T>: the percentage of each <T k="bet-wager">bet</T> the casino keeps on
        average. It&#39;s small — often 1–3% — which is why you can absolutely win on any given night. But it never
        sleeps, and over thousands of bets it grinds. You can&#39;t eliminate it (short of counting cards); what
        you <em>can</em> control is how big it is.
      </p>
      <h2>Your decisions change the price</h2>
      <p>
        In slots, craps or baccarat, once the bet is down there&#39;s nothing left to decide — the edge is fixed.
        The games on this site are different: <strong>you make choices after the cards come out, and every choice
        moves the edge.</strong> The advertised number (the <T k="implied-vs-actual">implied edge</T>) assumes
        perfect play. Play by gut feel and your <em>actual</em> edge can easily be three or four times worse — a
        tax made entirely of avoidable mistakes. This site shows both numbers side by side, live, as you play.
      </p>
      <h2>Expected value: the only math you need</h2>
      <p>
        Every option — hit or stand, hold or draw, bet or fold — has an{' '}
        <T k="expected-value">expected value (EV)</T>: what it would win or lose <em>on average</em> if you made
        that same choice in that same spot forever. The right play is simply the option with the highest EV.
        It will still lose plenty of individual hands — that&#39;s <T k="variance">variance</T>, and it&#39;s
        normal. Judge your decisions by the math, not by one result: doubling 11 against a 6 is correct every
        single time, including the times it loses.
      </p>
      <h2>Where to start</h2>
      <p>
        Blackjack is the classic first study — one chart covers everything. Video poker rewards it most per hour
        of study. If you like the poker pits, Ultimate Texas Hold&#39;em has the most interesting decisions, and
        Three Card Poker takes five minutes to master, literally. And even though there&#39;s no strategy that
        beats them, the <a href="/learn/slots">slots lesson</a> explains how the machines actually work — which
        progression meters are real, what volatility costs you — so you can decide if and what to play with open
        eyes.
      </p>
      <p>
        Beyond the games themselves, three lessons cover the money side: <a href="/learn/bankroll">bankroll and
        variance math</a> (what a session really costs and why betting systems fail),{' '}
        <a href="/learn/paytables">reading pay tables</a> (the five-minute skill that saves more than any chart),
        and the <a href="/learn/myths">casino myths</a> that quietly pay for the chandeliers.
      </p>
    </>
  );
}

// ---------------------------------------------------------------- page

export const TOPICS: Record<string, { component: () => JSX.Element; title: string; description: string; nav: string }> = {
  '': {
    component: LearnIndex,
    title: `Casino Strategy School — Learn Perfect Play | ${SITE_NAME}`,
    description:
      'New to casino games? Learn what house edge and expected value actually mean, then study optimal strategy for blackjack, video poker, Ultimate Texas Hold\'em and Three Card Poker.',
    nav: 'Start Here',
  },
  blackjack: {
    component: BlackjackLesson,
    title: `Blackjack Basic Strategy Chart (6-Deck, S17) | ${SITE_NAME}`,
    description:
      'Beginner-friendly blackjack basic strategy: how to read the chart, hard totals, soft totals and pairs — generated by the same EV engine that grades your practice hands.',
    nav: 'Blackjack',
  },
  videopoker: {
    component: VideoPokerLesson,
    title: `Video Poker Strategy — JoB 9/6, Bonus, DDB, Deuces Wild | ${SITE_NAME}`,
    description:
      'Plain-English hold-priority strategy for Jacks or Better 9/6, Bonus Poker 8/5, Double Double Bonus and full-pay Deuces Wild video poker.',
    nav: 'Video Poker',
  },
  uth: {
    component: UthLesson,
    title: `Ultimate Texas Hold'em Strategy — 4x Preflop Chart & River Rule | ${SITE_NAME}`,
    description:
      "Ultimate Texas Hold'em explained for beginners: how the ante, blind and play bets work, when to bet 4x, 2x, 1x and when to fold.",
    nav: "Ultimate Hold'em",
  },
  threecard: {
    component: ThreeCardLesson,
    title: `Three Card Poker Strategy — The Q-6-4 Rule | ${SITE_NAME}`,
    description:
      'Three Card Poker for beginners: how ante, play and the dealer qualification rule work, and why Queen-6-4 is the exact line between playing and folding.',
    nav: 'Three Card',
  },
  slots: {
    component: SlotsLesson,
    title: `Slot Machines Explained — Types, Volatility, Real vs Fake Progression | ${SITE_NAME}`,
    description:
      'How slot machines really work: RNG myths, machine types, progressive jackpots, persistent-state vs perceived-persistence meters, and how to pick a slot that matches your risk tolerance.',
    nav: 'Slots',
  },
  bankroll: {
    component: BankrollLesson,
    title: `Bankroll & Variance Math — Session Cost, Swings, Betting Systems | ${SITE_NAME}`,
    description:
      'How much a casino session really costs: expected loss vs variance, how to size a bankroll for blackjack, video poker and slots, and the exact math of why betting systems like the Martingale fail.',
    nav: 'Bankroll',
  },
  paytables: {
    component: PaytablesLesson,
    title: `How to Read Casino Pay Tables — 9/6 vs 8/5, 3:2 vs 6:5 | ${SITE_NAME}`,
    description:
      'The five-minute skill that beats any strategy chart: reading video poker pay tables (9/6 vs 8/5 Jacks or Better), spotting 6:5 blackjack, max-coin royal payouts and why side bets are the house\'s best friend.',
    nav: 'Pay Tables',
  },
  myths: {
    component: MythsLesson,
    title: `Casino Myths vs. the Math — Due Machines, Systems, Insurance | ${SITE_NAME}`,
    description:
      'The most expensive casino myths, debunked with real math: the gambler\'s fallacy, third-base blame, blackjack insurance, betting systems, slot timing myths and the truth about card counting.',
    nav: 'Myths',
  },
  glossary: {
    component: GlossaryLesson,
    title: `Casino Terms Glossary — House Edge, EV, Odds Explained | ${SITE_NAME}`,
    description:
      'Plain-English definitions of casino terms: house edge, expected value, odds, variance, ante, blind, pay table, kicker, outs and more.',
    nav: 'Glossary',
  },
};

// ---------------------------------------------------------------- articles

export const ARTICLES_INDEX = {
  title: `Casino Strategy Articles — Deep Dives on the Math | ${SITE_NAME}`,
  description:
    'Long-form articles on casino math: what 6:5 blackjack really costs, the UTH 4x chart hand by hand, why full-pay Deuces Wild pays over 100%, how to prepare for a first casino trip, and more.',
  nav: 'Articles',
  published: '2026-09-28',
};

function ArticlesIndex() {
  return (
    <>
      <h1>Articles</h1>
      <p className="lede">
        Deeper dives than the lessons: one question per article, answered with the actual math. New pieces are
        added regularly — each carries its publication date and the date it was last checked.
      </p>
      <ul className="article-list">
        {ARTICLES.map((a) => (
          <li key={a.slug}>
            <a className="article-card" href={`/learn/${a.slug}`}>
              <span className="article-card-title">{a.title}</span>
              <span className="article-card-desc">{a.description}</span>
              <span className="article-card-meta">
                {formatDate(a.updated)} · {a.readingMinutes} min read
              </span>
            </a>
          </li>
        ))}
      </ul>
    </>
  );
}

function ArticleBody({ article }: { article: Article }) {
  const Comp = article.component;
  return (
    <article className="learn-article">
      <h1>{article.title}</h1>
      <Byline published={article.published} updated={article.updated} minutes={article.readingMinutes} />
      <Comp />
      <p className="article-back">
        <a href="/learn/articles">← All articles</a>
      </p>
    </article>
  );
}

// ---------------------------------------------------------------- page

export function LearnPage({ topic }: { topic: string }) {
  const article = ARTICLES.find((a) => a.slug === topic);
  const isArticlesIndex = topic === 'articles';
  const entry = article || isArticlesIndex ? null : (TOPICS[topic] ?? TOPICS['']);
  const title = article ? `${article.title} | ${SITE_NAME}` : isArticlesIndex ? ARTICLES_INDEX.title : entry!.title;
  const description = article ? article.description : isArticlesIndex ? ARTICLES_INDEX.description : entry!.description;
  const [sheetEntry, setSheetEntry] = useState<GlossaryEntry | null>(null);
  useEffect(() => {
    document.title = title;
    const meta = document.querySelector('meta[name="description"]');
    if (meta) meta.setAttribute('content', description);
    // support deep links to glossary anchors after SPA navigation
    if (window.location.hash) {
      const el = document.getElementById(window.location.hash.slice(1));
      if (el) el.scrollIntoView();
    }
  }, [title, description]);
  const Body = entry?.component;
  const articlesActive = Boolean(article) || isArticlesIndex;
  return (
    <TermSheetCtx.Provider value={setSheetEntry}>
      <div className="learn-page">
        <nav className="learn-nav">
          {Object.entries(TOPICS).map(([key, t]) => (
            <Fragment key={key}>
              {key === 'glossary' && (
                <a href="/learn/articles" className={articlesActive ? 'active' : ''}>
                  {ARTICLES_INDEX.nav}
                </a>
              )}
              <a href={key ? `/learn/${key}` : '/learn'} className={entry === t ? 'active' : ''}>
                {t.nav}
              </a>
            </Fragment>
          ))}
        </nav>
        {article ? <ArticleBody article={article} /> : isArticlesIndex ? <ArticlesIndex /> : Body ? <Body /> : null}
      </div>
      <TermSheet entry={sheetEntry} onClose={() => setSheetEntry(null)} />
    </TermSheetCtx.Provider>
  );
}
