import { useEffect, useMemo } from 'react';
import { actionEVs, bestAction, HandState } from '../lib/blackjack/ev';
import { SITE_NAME } from '../config';

// ---------------------------------------------------------------- helpers

const DEALER_UPS = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11];
const UP_LABELS = ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'A'];

type Cell = 'H' | 'S' | 'D' | 'Ds' | 'P';

function decide(state: HandState, up: number): Cell {
  const evs = actionEVs(state, up);
  const best = bestAction(evs);
  if (best === 'split') return 'P';
  if (best === 'double') return evs.stand! > evs.hit! ? 'Ds' : 'D';
  return best === 'hit' ? 'H' : 'S';
}

function useBlackjackCharts() {
  return useMemo(() => {
    const hard: { label: string; cells: Cell[] }[] = [];
    for (let total = 8; total <= 17; total++) {
      hard.push({
        label: String(total),
        cells: DEALER_UPS.map((up) =>
          decide({ total, soft: false, pairValue: null, isTwoCards: true, canSplit: false }, up),
        ),
      });
    }
    const soft: { label: string; cells: Cell[] }[] = [];
    for (let total = 13; total <= 20; total++) {
      soft.push({
        label: `A,${total - 11}`,
        cells: DEALER_UPS.map((up) =>
          decide({ total, soft: true, pairValue: null, isTwoCards: true, canSplit: false }, up),
        ),
      });
    }
    const pairs: { label: string; cells: Cell[] }[] = [];
    for (const v of [2, 3, 4, 5, 6, 7, 8, 9, 10, 11]) {
      const total = v === 11 ? 12 : v * 2;
      pairs.push({
        label: v === 11 ? 'A,A' : `${v},${v}`,
        cells: DEALER_UPS.map((up) =>
          decide({ total, soft: v === 11, pairValue: v, isTwoCards: true, canSplit: true }, up),
        ),
      });
    }
    return { hard, soft, pairs };
  }, []);
}

function StratChart({ rows, caption }: { rows: { label: string; cells: Cell[] }[]; caption: string }) {
  return (
    <div className="table-scroll">
      <table className="strat-table">
        <caption style={{ captionSide: 'bottom', fontSize: 11, color: 'var(--text-dim)', paddingTop: 6 }}>
          {caption}
        </caption>
        <thead>
          <tr>
            <th className="rowhead">You</th>
            {UP_LABELS.map((u) => (
              <th key={u}>{u}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((r) => (
            <tr key={r.label}>
              <td className="rowhead">{r.label}</td>
              {r.cells.map((c, i) => (
                <td key={i} className={c}>
                  {c}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function Legend() {
  return (
    <div className="strat-legend">
      <span><span className="key" style={{ background: 'rgba(224,87,79,.28)' }} />H = Hit</span>
      <span><span className="key" style={{ background: 'rgba(76,186,119,.26)' }} />S = Stand</span>
      <span><span className="key" style={{ background: 'rgba(88,146,227,.3)' }} />D = Double (else hit) · Ds = Double (else stand)</span>
      <span><span className="key" style={{ background: 'rgba(217,171,74,.32)' }} />P = Split</span>
    </div>
  );
}

// ---------------------------------------------------------------- topics

function BlackjackLesson() {
  const charts = useBlackjackCharts();
  return (
    <>
      <h1>Blackjack Basic Strategy</h1>
      <p className="lede">
        Basic strategy is the mathematically best action for every combination of your hand and the dealer&#39;s
        upcard. The charts below are <strong>generated by this site&#39;s own expected-value engine</strong> — the
        same one that grades you at the table (6 decks, dealer stands on all 17s, double after split, no
        surrender) — so what you study here is exactly what the trainer expects.
      </p>
      <Legend />
      <h3>Hard totals (no ace, or ace counting as 1)</h3>
      <StratChart rows={charts.hard} caption="Hard 8 and below: always hit. Hard 18+: always stand." />
      <h3>Soft totals (ace counting as 11)</h3>
      <StratChart rows={charts.soft} caption="Soft 21 is just 21 — stand." />
      <h3>Pairs</h3>
      <StratChart rows={charts.pairs} caption="P = split. Where no P is shown, play the hand as its total." />
      <h2>The five rules people break most</h2>
      <ol>
        <li><strong>Always split aces and eights.</strong> Even against a 10 or an ace. 16 is the worst hand in the game — splitting the 8s turns it into two live hands.</li>
        <li><strong>Never split tens or fives.</strong> 20 is nearly the best hand you can hold; a pair of fives is just a 10 that wants to double.</li>
        <li><strong>Double 11 against everything</strong> (under these S17 rules) and 10 against everything but a dealer 10 or ace.</li>
        <li><strong>Hit soft 18 against 9, 10 or ace.</strong> A,7 feels comfortable; against big cards it&#39;s a loser standing pat. Against 3–6, double it.</li>
        <li><strong>Hit 12 against a dealer 2 or 3.</strong> Only start standing on 12 when the dealer shows 4, 5 or 6.</li>
      </ol>
      <p>
        Why it matters: basic strategy keeps the house edge around half a percent. Typical &quot;gut feel&quot; play
        gives up another 1.5–2%, which is 3–4× the casino&#39;s designed advantage — all from free, avoidable
        mistakes.
      </p>
      <a className="practice-cta" href="/blackjack">Practice blackjack →</a>
    </>
  );
}

function VideoPokerLesson() {
  return (
    <>
      <h1>Video Poker Strategy</h1>
      <p className="lede">
        Video poker is the rare casino game where the machine tells you the full pay table and the math is
        completely knowable. Each variant below lists hold priorities from top to bottom: find the{' '}
        <strong>first line that matches your dealt hand and hold those cards</strong>. These simplified lists give
        up only a few hundredths of a percent versus computer-perfect play — the trainer will flag the exceptions
        when they come up.
      </p>

      <h2>Jacks or Better (9/6) — 99.54% return</h2>
      <ol>
        <li>Royal flush, straight flush, four of a kind — keep the made hand</li>
        <li>Four to a royal flush (yes, even breaking a pat flush or straight)</li>
        <li>Full house, flush, straight, three of a kind</li>
        <li>Four to a straight flush</li>
        <li>Two pair</li>
        <li>High pair (jacks or better)</li>
        <li>Three to a royal flush</li>
        <li>Four to a flush</li>
        <li>Low pair (10s or worse)</li>
        <li>Four to an outside straight (e.g. 6-7-8-9)</li>
        <li>Two suited high cards</li>
        <li>Three to a straight flush</li>
        <li>Two unsuited high cards (if three or more, keep the lowest two)</li>
        <li>Suited 10-J, 10-Q or 10-K</li>
        <li>One high card</li>
        <li>Nothing — discard all five</li>
      </ol>
      <p>
        The most-missed lines: <strong>a low pair beats holding one or two high cards</strong> (line 9 vs 11/13),
        and <strong>four to a flush beats a low pair</strong> — but a high pair beats four to a flush.
      </p>

      <h2>Bonus Poker (8/5) — 99.17% return</h2>
      <p>
        Bonus Poker pays extra for four aces (80×) and four 2s–4s (40×), funded by a smaller full house and flush.
        Strategy is <strong>nearly identical to Jacks or Better</strong> — use the list above. The differences are
        at the margins: hands that flirt with quad aces or low quads lean slightly more toward keeping the paying
        trips/pair rather than chasing flushes.
      </p>

      <h2>Double Double Bonus (9/6) — 98.98% return</h2>
      <p>Quad chasing changes real decisions here — four aces with a 2/3/4 kicker pays 400×:</p>
      <ol>
        <li>Keep <strong>three aces + a 2, 3 or 4</strong>: hold all four cards (the kicker is worth real money)</li>
        <li>With <strong>four of a kind (2s–4s) + an A–4 kicker</strong>, keep everything — with any other kicker, keep just the quads and draw at the premium kicker</li>
        <li><strong>Two pair, one of them aces: keep only the aces.</strong> In Jacks or Better you keep both pairs; here two pair pays just 1× so the shot at quad aces wins</li>
        <li>Otherwise play the Jacks or Better list</li>
      </ol>

      <h2>Deuces Wild (full pay) — 100.76% return</h2>
      <p>All four 2s are wild. Strategy is organized by how many deuces you&#39;re dealt:</p>
      <h3>Four deuces</h3>
      <ol><li>Hold the four deuces (200×); the fifth card doesn&#39;t matter</li></ol>
      <h3>Three deuces</h3>
      <ol>
        <li>Wild royal or five of a kind — keep it</li>
        <li>Otherwise hold <strong>just the three deuces</strong></li>
      </ol>
      <h3>Two deuces</h3>
      <ol>
        <li>Any made four of a kind or better — keep it</li>
        <li>Four to a royal</li>
        <li>Otherwise hold <strong>just the two deuces</strong> (never keep a pair alongside them)</li>
      </ol>
      <h3>One deuce</h3>
      <ol>
        <li>Any made three of a kind or better (a deuce + a pair <em>is</em> trips — keep all three)</li>
        <li>Four to a royal or four to a straight flush</li>
        <li>Three to a royal; three to a straight flush with two straight-flush cards 6-7 or better</li>
        <li>Otherwise hold <strong>the deuce alone</strong></li>
      </ol>
      <h3>No deuces</h3>
      <ol>
        <li>Made pays: three of a kind or better — keep</li>
        <li>Four to a royal or straight flush</li>
        <li>One pair (never two pair — <strong>keep only one of the two pairs</strong>, two pair doesn&#39;t pay here)</li>
        <li>Four to a flush or outside straight; three to a royal or straight flush</li>
        <li>Nothing — draw five. Unsuited high cards are worthless in Deuces Wild; there is no jacks-or-better pay</li>
      </ol>
      <a className="practice-cta" href="/videopoker">Practice video poker →</a>
    </>
  );
}

function UthLesson() {
  return (
    <>
      <h1>Ultimate Texas Hold&#39;em Strategy</h1>
      <p className="lede">
        The whole game is three decisions, and the guiding principle is: <strong>the earlier you bet, the more you
        can bet — so bet big early with any advantage.</strong> Checking &quot;to see what happens&quot; with a
        raise-worthy hand is the single most expensive habit in this game.
      </p>
      <h2>Preflop: bet 4× or check</h2>
      <p>Bet the full 4× (never 3×) with:</p>
      <ol>
        <li><strong>Any pair of 3s or better</strong> (check deuces)</li>
        <li><strong>Any ace</strong></li>
        <li><strong>Suited kings</strong> — all of them; unsuited kings with a 5 or better</li>
        <li><strong>Suited queens with a 6+</strong>; unsuited queens with an 8+</li>
        <li><strong>Suited jacks with an 8+</strong>; unsuited J-10</li>
      </ol>
      <p>Everything else checks. Roughly 38% of hands raise — if that feels aggressive, you&#39;re playing it right.</p>
      <h2>Flop (after checking): bet 2× or check</h2>
      <ol>
        <li><strong>Two pair or better</strong> — bet</li>
        <li><strong>A hidden pair</strong> (your hole card pairs the board, or a pocket pair — except pocket deuces) — bet</li>
        <li><strong>Four to a flush including a hidden 10 or better</strong> — bet</li>
        <li>Otherwise check</li>
      </ol>
      <p>&quot;Hidden&quot; matters: if the pair is entirely on the board, the dealer has it too.</p>
      <h2>River (after checking twice): bet 1× or fold</h2>
      <ol>
        <li><strong>Any hidden pair or better</strong> — bet</li>
        <li>
          Otherwise count <strong>dealer outs</strong>: cards that would give the dealer a winning pair. If fewer
          than 21 of the 45 unseen cards beat you, bet; otherwise fold. Quick version: with nothing, bet only when
          the board is paired-and-ragged enough that you&#39;ll often tie by playing the board.
        </li>
      </ol>
      <p>
        Folding costs a fixed 2 antes. Betting 1× with a live hand is usually cheaper than it feels — the trainer
        computes the exact number for every river you face (990 possible dealer hands), so drill until the 21-out
        boundary is instinct.
      </p>
      <h2>The blind is the house&#39;s rake — beat it with big hands</h2>
      <p>
        The blind only pays on a straight or better, which is why optimal play is aggressive preflop: winning 4×
        play-bet money is how you offset all the small blind losses. Optimal play holds the house to about 2.2% of
        one ante (about 0.53% of total money bet).
      </p>
      <a className="practice-cta" href="/uth">Practice Ultimate Texas Hold&#39;em →</a>
    </>
  );
}

function ThreeCardLesson() {
  return (
    <>
      <h1>Three Card Poker Strategy</h1>
      <p className="lede">
        One decision: play (matching your ante) or fold. The entire optimal strategy is a single sentence —
        <strong> play with Queen-6-4 or better, fold anything worse.</strong>
      </p>
      <h2>How to read Q-6-4</h2>
      <p>
        Compare your three cards to Q-6-4 from the highest card down: any pair or better always plays. Q-7-2 plays
        (the 7 beats the 6 before the third card matters). Q-6-4 exactly plays. Q-6-3 folds. J-10-9 folds — any
        jack-high or worse is a fold, no matter how pretty.
      </p>
      <h2>Why not &quot;always play&quot; or &quot;mimic the dealer&quot;?</h2>
      <p>
        Playing every hand gives the house about 7.7%; folding everything under a pair gives up even more. Q-6-4
        holds it to 3.37% of the ante (about 2% of total money at risk) because of the qualification rule: when the
        dealer doesn&#39;t open with queen-high, your ante wins even with garbage — so hands slightly worse than
        the dealer&#39;s qualifying floor are still worth a bet.
      </p>
      <h2>The ante bonus is free money</h2>
      <p>
        A straight or better pays a bonus (straight 1×, trips 4×, straight flush 5×) <strong>even if the dealer
        beats you</strong>. It&#39;s automatic — no decision needed, just a reason the game is friendlier than it
        looks when you&#39;re running hot.
      </p>
      <a className="practice-cta" href="/threecard">Practice Three Card Poker →</a>
    </>
  );
}

function LearnIndex() {
  return (
    <>
      <h1>The Strategy School</h1>
      <p className="lede">
        Every game here has a mathematically correct way to play it, worked out decades ago and verifiable to the
        decimal. Study the write-up, then take it to the table — the trainer grades every decision against the
        same math and shows you what each mistake costs. Start with the game you actually play.
      </p>
      <h2>What &quot;house edge&quot; really means</h2>
      <p>
        The advertised house edge of a game assumes <strong>perfect play</strong>. Blackjack&#39;s famous
        &quot;half a percent&quot; belongs only to people who never mis-play a hand; the average tourist hands over
        2% or more. The gap between the edge on the sign and the edge you actually pay is made entirely of
        decisions — which means it&#39;s the one part of the casino you control.
      </p>
      <h2>Expected value in one paragraph</h2>
      <p>
        Every option you have — hit or stand, hold or draw, bet or fold — has an expected value (EV): the average
        amount you&#39;d win or lose making that choice in the same spot forever. The right play is simply the
        option with the highest EV. It won&#39;t win every hand (that&#39;s variance); it wins the most over
        thousands of hands. When this site gives you a 👎 it also shows the EV of what you did and what you should
        have done, in dollars — so you learn to feel the price of a bad habit.
      </p>
    </>
  );
}

// ---------------------------------------------------------------- page

const TOPICS: Record<string, { component: () => JSX.Element; title: string; description: string; nav: string }> = {
  '': {
    component: LearnIndex,
    title: `Casino Strategy School — Learn Perfect Play | ${SITE_NAME}`,
    description:
      'Study optimal casino strategy: blackjack basic strategy charts, video poker hold priorities, Ultimate Texas Hold\'em raise rules and Three Card Poker Q-6-4 — then practice with graded decisions.',
    nav: 'Overview',
  },
  blackjack: {
    component: BlackjackLesson,
    title: `Blackjack Basic Strategy Chart (6-Deck, S17) | ${SITE_NAME}`,
    description:
      'Full blackjack basic strategy charts for hard totals, soft totals and pairs — generated by the same EV engine that grades your practice hands.',
    nav: 'Blackjack',
  },
  videopoker: {
    component: VideoPokerLesson,
    title: `Video Poker Strategy — JoB 9/6, Bonus, DDB, Deuces Wild | ${SITE_NAME}`,
    description:
      'Hold-priority strategy lists for Jacks or Better 9/6, Bonus Poker 8/5, Double Double Bonus and full-pay Deuces Wild video poker.',
    nav: 'Video Poker',
  },
  uth: {
    component: UthLesson,
    title: `Ultimate Texas Hold'em Strategy — 4x Preflop Chart & River Rule | ${SITE_NAME}`,
    description:
      "When to bet 4x preflop, 2x on the flop, and 1x or fold on the river in Ultimate Texas Hold'em — the optimal strategy explained.",
    nav: "Ultimate Hold'em",
  },
  threecard: {
    component: ThreeCardLesson,
    title: `Three Card Poker Strategy — The Q-6-4 Rule | ${SITE_NAME}`,
    description:
      'Why Queen-6-4 is the mathematically exact line between playing and folding in Three Card Poker, and what the ante bonus is worth.',
    nav: 'Three Card',
  },
};

export function LearnPage({ topic }: { topic: string }) {
  const entry = TOPICS[topic] ?? TOPICS[''];
  useEffect(() => {
    document.title = entry.title;
    const meta = document.querySelector('meta[name="description"]');
    if (meta) meta.setAttribute('content', entry.description);
  }, [entry]);
  const Body = entry.component;
  return (
    <div className="learn-page">
      <nav className="learn-nav">
        {Object.entries(TOPICS).map(([key, t]) => (
          <a key={key} href={key ? `/learn/${key}` : '/learn'} className={entry === t ? 'active' : ''}>
            {t.nav}
          </a>
        ))}
      </nav>
      <Body />
    </div>
  );
}
