import { SITE_NAME } from './config';

/** titles/descriptions for the non-game, non-learn routes — used by the SPA
 *  (document.title on navigation) and by the build-time prerenderer. */
export const STATIC_PAGES: { path: string; title: string; description: string }[] = [
  {
    path: '',
    title: `${SITE_NAME} — Free Casino Strategy Trainer | Blackjack, Video Poker, Ultimate Texas Hold'em`,
    description:
      "Free casino strategy trainer. Every blackjack, video poker, Ultimate Texas Hold'em and Three Card Poker decision graded against the real math. No real money, ever.",
  },
  {
    path: 'card',
    title: `Blackjack Strategy Card — Quick Reference | ${SITE_NAME}`,
    description:
      'Pocket-sized blackjack basic strategy card for 6-deck S17 DAS games: hard totals, soft totals and pairs, generated by an exact expected-value engine.',
  },
  {
    path: 'about',
    title: `About ${SITE_NAME} — Who Builds This & Where the Math Comes From`,
    description:
      'Who runs A Few Good Hands, why it exists, and how every strategy grade is computed by exact enumeration rather than simulation. Free, play-money only, no real gambling.',
  },
  {
    path: 'contact',
    title: `Contact ${SITE_NAME}`,
    description:
      'Get in touch about math errors, bugs, or games and pay tables you want added to the free casino strategy trainer.',
  },
  {
    path: 'privacy',
    title: `Privacy Policy | ${SITE_NAME}`,
    description:
      'What A Few Good Hands collects (nothing directly), how play data stays in your own browser, and how Google AdSense advertising cookies work on this site.',
  },
  {
    path: 'legal',
    title: `Legal & Disclaimers | ${SITE_NAME}`,
    description:
      'Legal notices for A Few Good Hands: play-money educational trainer, no real-money gambling, trademark and copyright information, and terms of use.',
  },
];

export const STATIC_META = new Map(STATIC_PAGES.map((p) => [p.path, p]));
